### ISSUE TITLE
Github link at bottom of page is outdated

### ISSUE THREAD

**Issue by Kristine1975** [OldTimes-Software/thedatadungeon.com#13]
**Describe the bug**
At the bottom of each page is a section with links to, among others, an RSS Feed and Github. The Github link is `https://github.com/OldTimes-Software`, which no longer exists.

**To Reproduce**
1. Go to https://archive.thedatadungeon.com/index.html
2. Scroll down to the bottom of the page
3. Click on "GitHub"
4. Github says "Page not found"

**Expected behavior**
The Github link should go to https://github.com/TalonBraveInfo/thedatadungeon.com

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser Firefox, Safari
 - Version 113.0.1 (Firefox), 12.1.2 (Safari)

**Comment by hogsy** [comment]
Fixed!
