### ISSUE TITLE
Strange sorting by date

### ISSUE THREAD

**Issue by Kristine1975** [OldTimes-Software/thedatadungeon.com#14]
**Describe the bug**

**To Reproduce**
1. Go to https://archive.thedatadungeon.com/unreal_1998.html
2. Click on the "Date" header to sort ascending by date
3. The files are sorted somewhat by their date, but not always. E.g. "1995-12-06 => 1995-09-28 => 1995-11-23", "1997-06-17 => 1997-05-24 => 1997-05-25" and "1999-05-01 => 1999-05-27 => 1999-05-01"

**Expected behavior**
The list should be sorted by the date.

**Screenshots**
![sorting](https://github.com/user-attachments/assets/182b6791-347b-4cf8-81f6-f774b0777967)

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser Firefox, Safari
 - Version 113.0.1 (Firefox), 12.1.2 (Safari)

**Comment by hogsy** [comment]
Thanks, I'll check this out over the weekend :+1:

**Comment by Kristine1975** [comment]
I looked a bit into it, and it's probably because to determine the sort function, `sorttable.js` looks through all values in a column and checks if they're numeric or one of several date formats (not yyyy-mm-dd though); see function `guessType`, starting at line 166.

Because there's an entry "1996", and because yyyy-mm-dd isn't a supported date format, the column type is determined to be numeric. So the column is effectively sorted only by the year.

Since the date column also contains "Pending", it's probably best to sort it alphanumerically, which works with yyyy-mm-dd dates, too.

**Comment by hogsy** [comment]
Fixed!
