### ISSUE TITLE
Funky effect on dx7sdk "DirectX File Cube Example" page

### ISSUE THREAD

**Issue by madebr** [OldTimes-Software/thedatadungeon.com#16]
**Describe the bug**
Text scrolls and does not scroll.

**To Reproduce**
1. Go to https://library.thedatadungeon.com/directx7/dxmedia/foundation/d3drm/oview/xfileExample.htm
2. Scroll page

**Expected behavior**
Text scrolls

**Screenshots**
![image](https://github.com/user-attachments/assets/255b990a-62e1-47a3-bc3d-47feb39dc926)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: firefox
 - Version: 132.0.1

**Comment by solemnwarning** [comment]
Thats fixed, thanks for pointing it out
