### ISSUE TITLE
Links at top of page don't scrolls the page to the section

### ISSUE THREAD

**Issue by madebr** [OldTimes-Software/thedatadungeon.com#17]
**Describe the bug**
https://library.thedatadungeon.com/directx7/dxmedia/foundation/d3drm/ref/Callbacks.htm

At the top of this page, a list overview of  function typedefs is given.
Clicking on these does not move the page to its contents.

At the top of this page, 

**To Reproduce**
1. Go to https://library.thedatadungeon.com/directx7/dxmedia/foundation/d3drm/ref/Callbacks.htm
2. Click on `D3DRMLOADTEXTURECALLBACK`
**Expected behavior**
The page scrolls down to `D3DRMLOADTEXTURECALLBACK`

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox 
 - Version: 132.0.1

**Additional context**

This issue occurs on multiple pages, so you might have to run some regex to find those.
https://library.thedatadungeon.com/directx7/dxmedia/foundation/d3drm/oview/xfileExample.htm
https://library.thedatadungeon.com/directx7/dxmedia/foundation/d3drm/ref/functions.htm
https://library.thedatadungeon.com/directx7/dxmedia/foundation/d3drm/ref/ReturnValues.htm (DD_OK)
https://library.thedatadungeon.com/directx7/dxmedia/foundation/d3drm/vbd3drm/Enums.htm

**Comment by solemnwarning** [comment]
Fixed!
