### ISSUE TITLE
Entry "Stars of Blood" exists twice

### ISSUE THREAD

**Issue by Kristine1975** [OldTimes-Software/thedatadungeon.com#2]
**Describe the bug**
Entry "Stars of Blood" exists twice and points to the same page

**To Reproduce**
1. Go to https://archive.thedatadungeon.com/index.html
2. Scroll down to 'Stars of Blood'
4. Find two entries 'Stars of Blood', both pointing to https://archive.thedatadungeon.com/stars_of_blood_cancelled.html

**Comment by hogsy** [comment]
Aha, thanks for spotting that! Somehow totally missed it. Will look into it.

**Comment by hogsy** [comment]
Okay, fortunately it's just a case that it accidently got added to the [root.dd](https://github.com/OldTimes-Software/thedatadungeon.com/blob/master/data/root.dd) file twice it seems, obviously had a brain fart. Will amend after work.
