### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by Kristine1975** [OldTimes-Software/thedatadungeon.com#6]
**Is your feature request related to a problem? Please describe.**
To get notified of changes/new entries, I added https://archive.thedatadungeon.com to my news reader. Unfortunately it doesn't seem to provide an RSS feed.

**Describe the solution you'd like**
It would be nice if The Data Dungeon provided an RSS/Atom feed containing new entries.

**Describe alternatives you've considered**
I could manually check https://archive.thedatadungeon.com/changes.html from time to time.

**Comment by hogsy** [comment]
Sorry for the wait on this one, I've been caught up with all the recent leaks so it tumbled down my list a little bit. This is now deploying to the live site (give it approx an hour or so from now as there are some big files slowing things down a little bit). I've updated the changelog page so each entry can be linked to (RSS feed utilises this).

In my great wisdom I missed the titles for each item too, so those will be fixed very shortly.

Let me know if you spot any issues.
