### ISSUE TITLE
Duke.Nukem.Endangered.Species-x0r_jmp.rar.sources has wrong Content-Type

### ISSUE THREAD

**Issue by Kristine1975** [OldTimes-Software/thedatadungeon.com#7]
**Describe the bug**
I clicked on https://archive.thedatadungeon.com/duke_nukem_endangered_species_cancelled/distributions/2001-10-30_microsoft_windows_prototype/duke.nukem.endangered.species-x0r_jmp.rar.sources to view the text file. Instead my browsers (Safari and Firefox) downloaded and saved it. `curl -v` showed that the server sends the file with `Content-Type: application/rar` instead of `text/plain`.

**Expected behavior**
The file's content type should be `text/plain`.

**Desktop (please complete the following information):**
 - OS: MacOS X 10.14
 - Browser: Safari 12.1.2, Firefox 106.0.5

P.S: Thank you for mirroring the file, and for the Data Dungeon in general!

**Comment by solemnwarning** [comment]
Fixed.
