### ISSUE TITLE
Size sorting bug

### ISSUE THREAD

**Issue by EnekoT2001** [OldTimes-Software/thedatadungeon.com#9]
**Describe the bug**
Filtering by size is broken, it just checks the first digit and doesn't keep KB/MB/GB in mind so for example 15GB will be marked lower than 7GB. or 90MB will be marked as bigger than 8GB

Another issue i have is that the download is very slow and shared across any other traffic, i tried downloading a thing yesterday, it went at 600-700KB/s and if i tried to download another thing on another device using mobile data (so different IP completely) the bandwidth would get shared across the two devices so i'd get 300 and 300. But right now i guess more people are downloading and its working at 75KB/s idk if this is just bc the servers are very limited (which i understand bc servers are expensive) or a bug in the software, just wanted to mention it too bc I'm looking at spending over two weeks downloading what i want 

**To Reproduce**
Bug 1: Sort any list of files by size
Bug 2: Try to download anything

**Expected behavior**
File sizes to work correctly
Downloads to not go so slow if possible

**Screenshots**
![image](https://user-images.githubusercontent.com/42989949/213690786-7df35177-454d-455e-8101-bbc4f7489474.png)
![image](https://user-images.githubusercontent.com/42989949/213691170-d8e0aa02-ec68-4efd-b612-ba0dc3c99f61.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 109.0.5414.74 

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus
 - OS: iOS 16.2
 - Browser Safari
 - Version Idk the one that comes in ios 16.2

**Additional context**

**Comment by hogsy** [comment]
@EnekoT2001 the issue with the speed should be resolved now, looks like it may have been a hardware issue with the server - will continue monitoring on our end.

With regards to sorting, I'm aware of it and it's on my list to resolve at some stage.

Update:

Looks like there's still a problem. We'll continue trying to fix it on our end and will let you know.

**Comment by EnekoT2001** [comment]
Just checked and it seems to download way faster but some files dont download at all (like [this one](https://archive.thedatadungeon.com/watch_dogs_2013/builds/2014-04-04_microsoft_xbox_360_mrc-cp-main-cg_14614/watch_dogs_04-04-2014mrc-cp-main-cg_14614.rar) for me at least). I could download a few already so no worries, i'll leave the others on jdownloader so when it works again they'll download. Thank you

**Comment by EnekoT2001** [comment]
right now the site is down if I use my residential IP address but if i use a vpn like Cloudflare Warp it works ok, it still has very slow download speeds, it starts downloading fast and after a few seconds it drops, i'll try to download what i have left this way to stop sucking bandwidth

**Comment by hogsy** [comment]
Just to give you an update, we seem to have a problem for sure and think our host is throttling us basically (though they won't admit it). We're currently looking to move to a different host. Unfortunately that's going to take a little bit of time so you'll have to bear with us.

**Comment by EnekoT2001** [comment]
Wow that’s so awful. And hey no worries, at least we caught them early, hope the migration goes as smoothly as possible and do let me know if I can do anything to help

**Comment by hogsy** [comment]
Sorry for the wait! 😅 

We found a new host and finally transferred everything over, so hopefully speeds should be more consistent now. Let us know if you have any problems.

**Comment by EnekoT2001** [comment]
Glad to see its all been resolved! and no worries about taking time, it must have been a mess, I'm just glad it's been fixed now.

I tried downloading one of the watchdogs builds to try and sure enough, it now works great, 16-22MB/s on chrome browser, I'm so happy to see these gaming history artifacts well preserved and easily accessible, thank you so much!

**Comment by hogsy** [comment]
Fixed!
